version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chorus-middleware
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
